### ISSUE TITLE
Data Issue: 'Protein Shaker Bottle' unable to be marked

### ISSUE THREAD

**Issue by DreamShark-Bytes** [AeonSake/acnh-catalogue-issues#10]
**Describe the bug**
No longer able to mark an item in the catalog as 'Owned'. This item was not introduced in 2.0 of Animal Crossing New Horizon (added in version 1.0.0)
Item name: Protein Shaker Bottle
URL: https://catalogue.ac/?i=7800-1
Occurs on Desktop and Mobile

**To Reproduce**
1. Search for "Protein Shaker Bottle"
2. Encounter Error/Issue
3. Click on Item
4. Continue to encounter Error/Issue

**Expected behavior**
Able to check mark the item from the search page and item's dedicated page

**Screenshots**
![ProteinShakerBottle-Listing](https://user-images.githubusercontent.com/70111379/140625672-91d0c110-14d6-4c4c-82e7-5afaa979b410.png)
![ProteinShakerBottle-DrillDown](https://user-images.githubusercontent.com/70111379/140625673-acbbee1c-ed41-47ba-bdb2-3ad373a2f619.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 95.0.4638.69 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 5
 - OS: Android 12
 - Browser Chrome
 - Version 95.0.4638.74

**Additional context**
n/a

**Comment by AeonSake** [comment]
Sorry about this, the bug has been fixed already and will be pushed with the next update.

**Comment by AeonSake** [comment]
Fixed in latest update (v3.142)
