### ISSUE TITLE
Feature Request: List What Villagers bring to Happy Home Paradise

### ISSUE THREAD

**Issue by PanoramicPanda** [AeonSake/acnh-catalogue-issues#11]
**Is your feature request related to a problem? Please describe.**
When a Villager comes to Happy Home Paradise, they come with some items to add to your Poki Catalogue. Eventually, you get the option to buy stuff from the Poki Catalogue directly.

**Describe the solution you'd like**
Being able to see on an item what Villager(s) bring the item to HHP (if any), to be able to find out which Amiibo I need to fish out for a particular item.

**Comment by AeonSake** [comment]
This feature has been implemented in the recent update (v3.195).
Items now list the residents who unlock the item and residents list their requested indoor/outdoor items and the unlocked items.
