### ISSUE TITLE
plain .txt does not import at all/catalogue not accurately displaying?

### ISSUE THREAD

**Issue by r6km** [AeonSake/acnh-catalogue-issues#12]
basically what the title says. plain .txt import doesn't work, or the import feature *does* work but the catalogue isn't accurately displaying what we've imported. im unable to tell which one it is but when i manually click on something to mark it as catalogued, it displays correctly after refreshing. 

**To Reproduce**
1. click import
2. select plain text in drop down menu
3. click next
4. set the data language to english US
5. type/copy paste any DIY and any amount, i used "coconut milk" and "clothesline" on their own line (one 2.0 item, one pre 2.0 item)
6. click next
7. click "DIY Recipe" on all imported diys
8. trying to use both merge or override gives the same result so pick either one
9. click import
10. refresh page to see that diys are not updated in dashboard and categories

**Expected behavior**
expected behavior is to have the catalogue correctly show that i do own the DIY by it being marked with the yellow check mark after importing plain.txt

**Desktop**
 - OS: windows 10
 - Browser: chrome
 - Version: 96.0

**Additional context**
tested with various quantities of DIYs, clicking "DIY Recipe" only. 1, then 2, then 100 and finally more than 100. ive deleted my cache, restarted browser, issue still persists. i do not own a smartphone so i was not able to figure out if this happens on mobile as well. minor suggestion 1: "check all" button when selecting "DIY Recipe" or "Item." minor suggestion 2: direct .txt file import, maybe google doc import too. minor suggestion 3: add the option to show items as a list rather than an array.

**Comment by AeonSake** [comment]
Thanks for the report, this issue should be fixed in the latest update (v3.199). Sorry for the inconvenience.
