### ISSUE TITLE
Feature Request: When Importing, Allow Auto Check of First Color/All Colors

### ISSUE THREAD

**Issue by PanoramicPanda** [AeonSake/acnh-catalogue-issues#13]
**Is your feature request related to a problem? Please describe.**
When going to import a lot of items, the dialogue pops up to choose the color you have for collection purposes. If you have a ton of items, this takes *forever*.

**Describe the solution you'd like**
A button to auto check first/auto check all would be so helpful - just auto selecting the first/all colors.

**Describe alternatives you've considered**
N/A

**Additional context**
Especially with the new stuff with Cyrus on Harv's, getting a new color of an item is easy enough anyway.

**Comment by AeonSake** [comment]
Implemented in latest update (v3.223), including the options to "select first variants", "select all variants", "select native variants" (if native variant is set), "select DIY recipes" and "deselect all".
