### ISSUE TITLE
Google Drive data does not update when changes are made

### ISSUE THREAD

**Issue by elisrahamim** [AeonSake/acnh-catalogue-issues#15]
**Describe the bug**
Google Drive data does not update/sync when changes are made.

**To Reproduce**
1. Click on any category or list.
2. Make a change such as checking off an item or increasing the quantity of something on a list.
3. Click "dashboard"
4. Wait for the blue syncing/loading logo in the top left corner to update.
5. A pop-up window appears that says:

> **Sync issue**
> Local data and data from Google Drive are different. Please choose an option to continue.
> - Keep local data, override Google Drive data
> - Keep Google Drive data, override local data
> - Merge data

6. No matter which option is chosen, the issue resurfaces when 1-4 are repeated.

**Expected behavior**
After making a change, the changes should sync with my Google Drive data. 

**Screenshots**
<img width="1434" alt="Screen Shot 2021-11-26 at 11 28 40 PM" src="https://user-images.githubusercontent.com/94283583/143673571-30365d78-943c-401f-afbf-f45ab718805a.png">

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser: Safari
 - Version 15.1
 

**Additional context**
- After making a change, I made sure to wait for the blue syncing logo to finish before clicking dashboard.
- This issue does not occur if a change is made while on the dashboard. (i.e. checking off an item on the "new items" widget).
- The option chosen in the pop-up works as expected (i.e. the data successfully merges or is overridden).

**Comment by AeonSake** [comment]
This issue should have been fixed in the latest update (v3.221). Please let me know whether your problem has been resolved with this.
