### ISSUE TITLE
"Exclude Bookmarked Items" Does Nothing

### ISSUE THREAD

**Issue by pdinius** [AeonSake/acnh-catalogue-issues#16]
**Describe the bug**
When you use the filters and click "Bookmarked" twice so it shows an "X", it should (I believe) exclude any items you've previously bookmarked but it seems to do nothing. Items with a star and without both appear in the search results regardless.

**To Reproduce**
1. Search for anything (e.g. "golden")
2. Open the filters menu on the left
3. Click the "Bookmarked" checkbox twice so it shows an "X" in the checkbox
4. All items in the search appear, bookmarked or otherwise.

**Screenshots**
![image](https://user-images.githubusercontent.com/51176584/143814346-9baa1094-8774-4d90-ae27-bd9d26a87314.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 94.0.2

**Comment by AeonSake** [comment]
Fixed in the latest update (v3.224). Thank you for the report and sorry for the inconvenience.
