### ISSUE TITLE
"Share search results" Option Does Nothing

### ISSUE THREAD

**Issue by pdinius** [AeonSake/acnh-catalogue-issues#17]
**Describe the bug**
After performing a search and adding filters, clicking the 3 dots menu that includes the options to Check/Uncheck search results or add all results to a list has an option to "Share search results" which seems to do nothing. There is a similar option on lists which lets you see all the items in a text list or an image but on the search page the option has no effect.

**To Reproduce**
1. Perform any search (and potentially add filters but not necessary)
2. Click on the 3 vertical dots menu in the top right of the search results
3. Choose the option to "Share search results"
4. No window or visual feedback appears

**Expected behavior**
A window should appear allowing you to see all the results in a text list or download an image with the items.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 95.0

**Comment by AeonSake** [comment]
Thanks for the bug report, I will add a dialog for this.
The current behavior for this option is that the serialized search query is copied to your clipboard.

**Comment by AeonSake** [comment]
Fixed/implemented as a popup message in the latest update (v3.258).
