### ISSUE TITLE
Plain Text DIY Import Failure for Variant Items (continuation from #12)

### ISSUE THREAD

**Issue by Stochast1c** [AeonSake/acnh-catalogue-issues#18]
**Describe the bug**
Continuing from #12, DIY recipes that produce objects that have variants causes the plain text import for that specific DIY to quietly fail.

**To Reproduce**
1. Plain Text import any diy item that has multiple variants (e.g. acoustic guitar)
2. Use the menu to select all DIY recipes
3. Only non variant DIY items have their recipe imported (i.e. if you try to import the diy for acorn pochette and acoustic guitar, only acorn pochette will import)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 96.0.4664.110
 - Catalogue Version: 3.252

**Comment by AeonSake** [comment]
Fixed in latest update (v3.253).
