### ISSUE TITLE
List Failed to Parse Items from Plain Text Import

### ISSUE THREAD

**Issue by Stochast1c** [AeonSake/acnh-catalogue-issues#19]
**Is your feature request related to a problem? Please describe.**
Slightly related to #18 (although I don't think that would have triggered here) items that fail to import are just enumerated and not actually displayed, making an import of a huge list impossible to debug what failed to import.

**Describe the solution you'd like**
A list of items from the import that failed to parse displayed.

**Comment by AeonSake** [comment]
Implemented in the latest update (v3.258).
