### ISSUE TITLE
Objects with the same name but different ids just chooses the first entry

### ISSUE THREAD

**Issue by Stochast1c** [AeonSake/acnh-catalogue-issues#20]
**Describe the bug**
When plain text importing, objects that have the same name but different ids will cause just the first entry to be chosen for the import even if a variant is specified that only exists for one of the latter ids and not the first entry.

**To Reproduce**
1. Plain Text import: Tank;brown

**Expected behavior**
Obviously no way to really fix this problem (and as far as I can tell in English the only problem entry *is* Tank), so instead throw an error as failed to parse and displayed the failures ala #19, for manual review.

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser Chrome
- Version 96.0.4664.110
- Catalogue Version: 3.252

**Comment by AeonSake** [comment]
Fixed in the latest update (v3.258). Entries with duplicate names are now all listed in the selection dialog.
