### ISSUE TITLE
Plain Text Import Removing Already Checked-off Variants If Importing Different Variant using Merge Import

### ISSUE THREAD

**Issue by Stochast1c** [AeonSake/acnh-catalogue-issues#21]
**Describe the bug**
When plain text importing any amount of items if you upload an item that already has other variants marked off, the existing variants are removed in favor of the new import when using the merge (default) option.

**To Reproduce**
1. Plain text Import any amount of items with at least one already having a variant marked off in your catalog with the default Merge option selected (e.g. ABD;yellow with a silver one checked off)
2. Either specify an unmarked variant or let the pop-up prompt you to select a variant
3. Import

**Expected behavior**
Merge Importing should just add the new variant into your catalog (or nothing if that variant was already marked)

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser Chrome
- Version 96.0.4664.110
- Catalogue Version: 3.252

**Additional context**
Last problem with importing I've noticed :)

**Comment by AeonSake** [comment]
Fixed in latest update (v3.253).
