### ISSUE TITLE
Lock up when the birthdays widget is set to "upcoming"

### ISSUE THREAD

**Issue by shello** [AeonSake/acnh-catalogue-issues#22]
**Describe the bug**
When the webapp is configured with the "Resident birthdays" widget set to "Upcoming", it freezes if the day is December 31st.

**To Reproduce**
1. Ensure you have the birthdays widget on the dashboard set to "upcoming";
2. Open catalogue.ac on Dec 31;
3. Webapp never stops loading, and locks up.

It's also possible to trigger this bug when the following happens:
1. Open catalogue.ac on Dec 31;
2. Click "Configure Dashboard";
3. Open the settings menu on the "Resident birthdays" widget, and select "Upcoming";
4. The webapp locks up.

**Expected behavior**
The app should load normally (or in the second case, keep functioning as normally, with the resident birthdays loaded)

**Workaround**
Using the Developer Tools to remove the `"birthdays"` element from the array value of `"order"` in the `dashboard` key of catalogue.ac's Local Storage ensures the app loads correctly.

**Desktop (please complete the following information):**
 - OS: Linux 5.10.88-2-lts
 - Browser: Firefox (stable), also tested on Google Chrome (stable)

**Smartphone:**
 - OS: Android 11
 - Browser: Firefox Mobile (stable), also tested on Google Chrome (stable)

**Additional context**
This seems to be a problem specifically on December 31, 2021. I was unable to test on other dates. This setting hasn't been a problem on any other days.

**Comment by AeonSake** [comment]
Thanks for the bug report, I'm very sorry this caused issues. It should now be fixed with the latest update (v3.259).

**Comment by shello** [comment]
I can confirm this is now fixed and the webapp loads correctly. That was incredibly fast!

Thanks a lot!
