### ISSUE TITLE
Golden ladder can't be marked /checked

### ISSUE THREAD

**Issue by doggy0524** [AeonSake/acnh-catalogue-issues#23]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AeonSake** [comment]
Golden ladder set-up kit (and other set-up kits) don't show up in the catalog that's why they are not checkable by default. However, you can enable the "Make all entries checkable" option in the settings menu to also show a checkmark on those types of entries.
