### ISSUE TITLE
Progress Dashboard - Reactions/Tools/Goods/Nook Miles(?) selection causes others to disappear

### ISSUE THREAD

**Issue by AlgebraManiacABC** [AeonSake/acnh-catalogue-issues#24]
**Describe the bug**
When customizing what shows up in the "Progress" widget in the Dashboard, selecting certain lists causes all other lists to hide.

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Configure Dashboard'
3. Click on the wrench
4. Select a few categories, then select one of the following:
* Reactions
* Tools/Goods
* Nook Miles (why is this in the NL catalog btw?)
5. Notice how the other selected categories disappear

**Expected behavior**
Reactions should be implemented and show correctly, as well as "Tools/Goods"
Nook Miles (I assume is here for NH) should not show if the catalog is in NL

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: Moto One Ace 5G
 - OS: Android 10 (QZKS30.Q4-40-95-4)
 - Browser Brave
 - Version 1.34.80 Chromium: 97.0.4692.71

**Additional context**
Only tried in Brave, if that's anything worth noting

**Comment by AeonSake** [comment]
I totally forgot to reply to this issue but the bug has been fixed (was caused by missing stats/tracker categories).
