### ISSUE TITLE
Add Happy Home Paradise Island Residents list?

### ISSUE THREAD

**Issue by portiapendragon** [AeonSake/acnh-catalogue-issues#27]
Would it be possible to add a Happy Home Paradise Island Residents list, like the Your Residents under Special Lists?

I know I can make a new custom list to add them, but with the lists I already have, they get kind of lost.  I just wondered if it was possible.  It'd be nice if I could mark who was roommates with whom, too, on the Special List and what job they're assigned to (nurse, doctor, teacher, etc), if any, in the island amenities.

It would need to allow special animals (like Isabelle and Lyle, in my case) be added to a list.  I have a custom list for my Happy Home Paradise villagers, and I can't add Isabelle and Lyle to the list because they aren't options (only their photos/posters).

**Comment by AeonSake** [comment]
Good idea, will see how I can incorporate this. Thanks for the suggestion!

**Comment by AeonSake** [comment]
Implemented in the latest update (v3.331).

**Comment by AeonSake** [comment]
Side note: special NPCs (Isabelle, etc.) are currently not part of the data set but I will check how I could incorporate this in the future.

**Comment by AeonSake** [comment]
Special NPCs are now also available as category and can be added to the special HHP list (v3.333).

**Comment by portiapendragon** [comment]
Thank you!  This is great!  😄
