### ISSUE TITLE
[Bug] Tools are not shown 

### ISSUE THREAD

**Issue by palex00** [AeonSake/acnh-catalogue-issues#3]
**Describe the bug**
When sorting for Tools, no items get shown when **any** progress filter is checked, even if "none checked" is selected.

**To Reproduce**
1. Hover over categories
2. Click on 'Tools'
3. See the error if "Progress"-criteria is already selected
4. Or if this doesn't happen yet: Select any "Progress"-filter.
5. See the bug: No tools get shown, no matter if selected or not, no matter the filter (except when no filter at all is selected).

**Expected behavior**
The tools should be shown.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 88.0.1 64-bit

**Additional context**

**Comment by AeonSake** [comment]
Fixed in latest update.
If the `Make all entries checkable` option is enabled, the progress filter will respect the progress on those entries and show up correctly in the search results.
