### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by faidtastic** [AeonSake/acnh-catalogue-issues#32]
**Is your feature request related to a problem? Please describe.**
Not a problem per se, but as I'm trying to finish my Critterpedia it would be convenient to not have to click on every critter to see if I can currently catch it. I have the critters on my dashboard but to know time of day to get them I have to click.

**Describe the solution you'd like**
It would be very cool to be able to select my (island's) time zone and have the widget on the dashboard highlight what critters can be caught at the time of day the page is loaded.

**Comment by AeonSake** [comment]
The new widget "critters available now" was added in the latest update (v3.348).
