### ISSUE TITLE
Missing/Wrong colored Items

### ISSUE THREAD

**Issue by Shizuzeru** [AeonSake/acnh-catalogue-issues#40]
Hello!
- Fizzy Apple juice is missing from the list. (New Year Seasonal)

- Wrong color of Purple Frilly knee-high socks.

Link and Pictures.

(The socks)
(https://catalogue.ac/i/c605-2)

(Fizzy apple juice.)
![bild](https://github.com/AeonSake/acnh-catalogue-issues/assets/157805332/5b3b6ee6-3192-45f1-9e3a-ce544bd7d1b7)

(Correct Purple Frilly knee-high socks)
![bild](https://github.com/AeonSake/acnh-catalogue-issues/assets/157805332/052575c8-4278-43f0-aa19-bbd8dfdbd601) 

Im unsure if i missed anything or if this the wrong place to ask/help. Please tell me if i should add anything :)

**Comment by AeonSake** [comment]
1) `Fizzy apple juice` is the GB-English name for it; in US-English it's called `Sparkling cider`. This is only one of several subtle regional differences between the languages and is the reason why the website supports all the game languages. I'm not sure _why_ Nintendo decided to rename the item but it is what it is. Make sure to select your language in the menu. If the region of your switch is not set to America, the default type of English will be the GB variant.<img width="777" alt="Bildschirmfoto 2024-01-26 um 13 52 22" src="https://github.com/AeonSake/acnh-catalogue-issues/assets/22562391/8d907cc2-8211-4782-ae24-78b955ed4d3a">


2. It's a bit hard to see but there is an actual difference between the pink and purple variants.<img width="598" alt="Screenshot 2024-01-26 140817" src="https://github.com/AeonSake/acnh-catalogue-issues/assets/22562391/687360e0-7681-49f7-b6a4-edfe2d2de4c6">


I appreciate the report though!

**Comment by Shizuzeru** [comment]
Oh I'm so sorry and thank you!
I now see what you meant by English US and English GB
And thank you for telling me. I really appreciate it~ 🙂

Have a nice day 😁
________________________________
Från: AeonSake ***@***.***>
Skickat: den 26 januari 2024 14:13
Till: AeonSake/acnh-catalogue-issues ***@***.***>
Kopia: Shizu ***@***.***>; Author ***@***.***>
Ämne: Re: [AeonSake/acnh-catalogue-issues] Missing/Wrong colored Items (Issue #40)


  1.  Fizzy apple juice is the GB-English name for it; in US-English it's called Sparkling cider. This is only one of several subtle regional differences between the languages and is the reason why the website supports all the game languages. I'm not sure why Nintendo decided to rename the item but it is what it is. Make sure to select your language in the menu. If the region of your switch is not set to America, the default type of English will be the GB variant.Bildschirmfoto.2024-01-26.um.13.52.22.png (view on web)<https://github.com/AeonSake/acnh-catalogue-issues/assets/22562391/8d907cc2-8211-4782-ae24-78b955ed4d3a>
  2.  It's a bit hard to see but there is an actual difference between the pink and purple variants.Screenshot.2024-01-26.140817.png (view on web)<https://github.com/AeonSake/acnh-catalogue-issues/assets/22562391/687360e0-7681-49f7-b6a4-edfe2d2de4c6>

I appreciate the report though!
