### ISSUE TITLE
Ability to change local calendar for dashboard

### ISSUE THREAD

**Issue by okurej** [AeonSake/acnh-catalogue-issues#41]
I recently started a new island in March because I was tired of the snow. However, on my dashboard, I am forced to view holiday items, villager birthdays, critters etc. for December, the current month as of writing this request. This makes the dashboard completely useless for me.

I searched the site high and low for a way to change the calendar to March 2025, but that doesn't seem to be the case. I don't know how deeply integrated the realtime (internet?) clock is into the site's programming, but being able to at least preview different months would be nice. Thank you.

**Comment by AeonSake** [comment]
When you press the `Configure Dashboard` button on the dashboard, there should be a widget called `Time Machine` that should satisfy the thing you are looking for. Changing the time in that widget (and checking the `Enable` checkbox) will change the reference time for all time-related data on the website (e.g., current critters/birthdays/events, etc.).

**Comment by okurej** [comment]
Ah okay, didn't see that. Granted it was late when I was looking so my mind kind of glazed over it

Thanks for your graceful answer to my ignorance lol
