### ISSUE TITLE
Feature Request: Make Amiibo-Items be possible to exlude in the stats menu

### ISSUE THREAD

**Issue by palex00** [AeonSake/acnh-catalogue-issues#5]
**Is your feature request related to a problem? Please describe.**
I don't have the Sanrio Amiibos, neither do I have many other AC Amiibos - so while Amiibo items (Posters, Sanrio collections, etc.) are trackable both in catalogue on the website, it gives a false sense of "missing out" on the 100%.

**Describe the solution you'd like**
Have an option to exclude Amiibo-Items (or maybe even just Sanrio-Items) from the stats menu, similarly to the "Exclude fake art" and "Exclude customizable things".

**Comment by AeonSake** [comment]
I forgot to close the issue but this feature was implemented with version v3.305.
