### ISSUE TITLE
Feature Request: Make a checkmark (or counter) to optionally track items in your storage - This will make things easier if you see someone who needs to catalog an item

### ISSUE THREAD

**Issue by Skormes** [AeonSake/acnh-catalogue-issues#7]
Make it possible to track items you have in your storage - This will help people keeping track of stuff they currently own.  
  
This will make it easier for completionist to track everything without the needage of more than one list (which will be annoying to track on e.g. a single phone). This will also make helping other easier. Because you can see, if you own a specific item in case someone wants to catalog it.

**Comment by AeonSake** [comment]
This feature has been implemented with version v3.317.
