### ISSUE TITLE
Item order slightly mismatched from in-game order

### ISSUE THREAD

**Issue by shello** [AeonSake/acnh-catalogue-issues#8]
**Describe the bug**
The website mostly nails down the sorting of items and variations as they're seen in-game, with the exception of names with dashes in them, which the game treats as spaces for the purpose of sorting them in a list. 

**To Reproduce**
1. On catalogue.ac, browse to the "rugs" section (Categories > Furniture > Rugs);
2. In-game, open Nook Shopping, select the "wallpaper, flooring and more" option, and switch to the "rugs" section;
2. Look for any pair of items with the same prefix but separated by a dash and a space each (for instance: "Red-design kitchen mat" and "Red message mat");
3. Compare how they're ordered between the list on catalogue.ac and in-game.

**Expected behavior**
The website would ideally follow the same sorting as the game, that is, treating dashes as spaces, and thus "Red-design kitchen mat" would come before "Red message mat", and not after all other "Red *" (without any dash) items.

**Comment by AeonSake** [comment]
Thanks for the report, I will look into this. It was terribly hard to get the sorting to this point (in all languages) already because I didn't want to include Nintendo's hard-coded string sorting table which would increase the size of the data model significantly.

**Comment by AeonSake** [comment]
I deployed a fix for this issue, I hope this solves your problem.

**Comment by shello** [comment]
@AeonSake It seems to be consistent with the game sorting now. Thanks a lot!
